#!/bin/sh

mkdir -pv $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_STATE_HOME
mkdir -pv $XDG_STATE_HOME/python
mkdir -pv $XDG_DATA_HOME/password-store
mkdir -pv $XDG_DATA_HOME/task
mkdir -pv $XDG_CONFIG_HOME/mblaze
mkdir -pv $XDG_CONFIG_HOME/gnupg
mkdir -pv $XDG_CONFIG_HOME/readline
mkdir -pv $XDG_CONFIG_HOME/ipython
mkdir -pv $XDG_CONFIG_HOME/vit
mkdir -pv ~/.local/share/icons ~/.local/share/fonts ~/.local/bin
mkdir -pv $GRIM_DEFAULT_DIR
mkdir -pv $XDG_DATA_HOME/go
mkdir -pv $XDG_DATA_HOME/go/mod
mkdir -pv ~/.local/state/vim
mkdir -pv ~/.local/share/vim/undo
mkdir -pv ~/.local/share/vim/backup
mkdir -p ~/dl

mkdir -pv $XDG_STATE_HOME/bash
# .bash_history must be manually moved

mkdir -p ~/.local/state/emacs/backups
mkdir -p ~/.config/emacs/bookmarks
