#!/bin/sh

mkdir -pv $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_STATE_HOME
mkdir -pv $XDG_STATE_HOME/python
mkdir -pv $XDG_DATA_HOME/password-store
mkdir -pv $XDG_DATA_HOME/task
mkdir -pv $XDG_CONFIG_HOME/mblaze
mkdir -pv $XDG_CONFIG_HOME/gnupg
mkdir -pv $XDG_CONFIG_HOME/readline
mkdir -pv $XDG_CONFIG_HOME/ipython
mkdir -pv $XDG_CONFIG_HOME/vit
mkdir -pv $XDG_CONFIG_HOME/sioyek
mkdir -pv $XDG_CONFIG_HOME/mpd
mkdir -pv $XDG_CONFIG_HOME/mpv
mkdir -pv $XDG_CONFIG_HOME/sv
mkdir -pv $XDG_CONFIG_HOME/river
mkdir -pv $XDG_CONFIG_HOME/qutebrowser
mkdir -pv $XDG_CONFIG_HOME/matplotlib/stylelib
mkdir -pv $XDG_CONFIG_HOME/mako
mkdir -pv $XDG_CONFIG_HOME/asymptote
mkdir -pv $XDG_CONFIG_HOME/kitty
mkdir -pv $XDG_CONFIG_HOME/hypr
mkdir -pv $XDG_CONFIG_HOME/i3
mkdir -pv $XDG_CONFIG_HOME/alacritty
mkdir -pv ~/.local/share/icons ~/.local/share/fonts ~/.local/bin
mkdir -pv $GRIM_DEFAULT_DIR
mkdir -pv $XDG_DATA_HOME/go/mod
mkdir -pv ~/.local/state/vim
mkdir -pv ~/.local/share/vim/undo
mkdir -pv ~/.local/share/vim/backup

mkdir -pv $XDG_STATE_HOME/bash
# .bash_history must be manually moved

mkdir -p ~/.local/state/emacs/backups
mkdir -p ~/.config/emacs/bookmarks

cd .config/sv
for i in *; do
	mkdir -pv "$XDG_CONFIG_HOME/sv/$i"
done
