" Settings
set encoding=UTF-8

set viminfo='32,<256,:256,/256,%
set viminfofile=~/.local/state/vim/viminfo
set backupdir=./.vimbackup,~/.local/share/vim/backup,.,~/tmp,~/ " ??
set undodir=~/.local/share/vim/undo
set undofile
set history=4096
set exrc
set secure

" ui options
set nu
set shortmess="atToO"
set wildmenu
set wildoptions=pum
set showcmd
set cursorline

" search options
set ignorecase
set smartcase
set hlsearch
set incsearch
set wrapscan

" Indentation options
set cindent
set autoindent
set noexpandtab
set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Options without 'set'
syntax on
nohlsearch

" Colorscheme
set termguicolors
set background=dark

runtime maps.vim
runtime plugins.vim

" Load plugins
runtime ftplugin/man.vim
let g:no_man_maps = 1
let g:ft_man_open_mode = 'tab'
