#!/bin/sh

. "$HOME/.profile"
. "$XDG_CONFIG_HOME/xinit/xinitrc_common"
# export SCREENLOCKER=slock

xset s 900 900

runsvdir "$SVDIR_X11" &>> "$XDG_STATE_HOME/runsvdir-x11.log" &
xrdb load "$XDG_CONFIG_HOME/xinit/xresources/Xresources"

i3
