SHELL_NAME="bash"

export HISTFILE=$XDG_STATE_HOME/bash/history
export HISTSIZE=-1
source $XDG_CONFIG_HOME/sh/colors.sh
source $XDG_CONFIG_HOME/sh/functions.sh
source $XDG_CONFIG_HOME/sh/aliases.sh
source $XDG_CONFIG_HOME/sh/functions.bash

[ -d "$XDG_STATE_HOME/bash" ] || mkdir "$XDG_STATE_HOME/bash"

shopt -s autocd
# shopt -s cdable_vars
shopt -s cdspell

shopt -s checkwinsize
shopt -s cmdhist

# shopt -s expand_aliases
shopt -s promptvars

shopt -s extglob

set -o noclobber

_bash_set_prompt
_bash_set_title_updater

# currently no way to disable fuzzy completion
# _bash_fzf_integration
_common_sh_init
